version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 25
    labels:
      - "dependencies"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 25
    ignore:
      # Dependabot isn't able to update this packages that do not match the
      # source, so anything with a version
      - dependency-name: "*.v*"
    labels:
      - "dependencies"
    groups:
      aws-sdk-go-v2:
        applies-to: version-updates
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
