# Telegraf configuration

# If this file is missing an [agent] section, you must first generate a
# valid config with 'telegraf -sample-config > telegraf.toml'

# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared plugins.

# Even if a plugin has no configuration, it must be declared in here
# to be active. Declaring a plugin means just specifying the name
# as a section with no variables. To deactivate a plugin, comment
# out the name and any variables.

# Use 'telegraf -config telegraf.toml -test' to see what metrics a config
# file would generate.

# One rule that plugins conform to is wherever a connection string
# can be passed, the values '' and 'localhost' are treated specially.
# They indicate to the plugin to use their own builtin configuration to
# connect to the local system.

# NOTE: The configuration has a few required parameters. They are marked
# with 'required'. Be sure to edit those to make this configuration work.

[tags]
    # dc = "us-east-1"

# Configuration for telegraf itself
[agent]
    interval = "10s"
    debug = false
    hostname = ""
    utc = true
    precision = "s"

# Configuration for influxdb server to send metrics to
[outputs]
[outputs.influxdb]
    # The full HTTP endpoint URL for your InfluxDB instance
    url = "http://localhost:8086" # required.

    # The target database for metrics. This database must already exist
    database = "telegraf" # required.

    # username = "telegraf"
    # password = "metricsmetricsmetricsmetrics"

    # Set the user agent for the POSTs (can be useful for log differentiation)
    # user_agent = "telegraf"

# PLUGINS

# Read metrics about cpu usage
[cpu]
    # Whether to report per-cpu stats or not
    percpu = true
    # Whether to report total system cpu stats or not
    totalcpu = true

# Read metrics about disk usage by mount point
[disk]
    # no configuration

# Read metrics about disk IO by device
[io]
    # no configuration

# Read metrics about memory usage
[mem]
    # no configuration

[system]
    # no configuration

[swap]
    # no configuration
