mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes

memcached:
    image: memcached
    ports:
        - "11211:11211"

postgres:
    image: postgres
    ports:
        - "5432:5432"

# advertised host env variable must be set at runtime, ie,
#   ADVERTISED_HOST=`boot2docker ip` docker-compose up -d
kafka:
    image: spotify/kafka
    ports:
        - "2181:2181"
        - "9092:9092"
    environment:
        ADVERTISED_HOST:
        ADVERTISED_PORT: 9092

opentsdb:
    image: lancope/opentsdb
    ports:
        - "24242:4242"

rabbitmq:
    image: rabbitmq:3-management
    hostname: docker_rabbit
    ports:
        - "15672:15672"
        - "5672:5672"

opentsdb:
    image: lancope/opentsdb
    ports:
        - "24242:4242"

redis:
    image: redis
    ports:
        - "6379:6379"
